const TicketsActionTypes = {
  ADD_TICKETS: "ADD_TICKETS",
  TICKETS_FETCH_FAILED: "TICKETS_FETCH_FAILED",
  TICKETS_FETCH_START: "TICKETS_FETCH_START",
  TICKETS_FETCH_SUCCESS: "TICKETS_FETCH_SUCCESS",
};

export default TicketsActionTypes;
